class QuestionCfg {
	public static readonly cfgs:any = {
		1:[
			{
				question:"诸葛氏是中国的一个复姓，以下四位姓诸葛的人中，哪一位不是诸葛亮的直系亲属？",
				selection:["诸葛瑾","诸葛丰","诸葛瞻","诸葛尚"],
				correct:0
			},
			{
				question:"诸葛亮死的时候，以下哪个人没在他的身边？",
				selection:["姜维","费祎","杨仪","魏延"],
				correct:3
			},
			{
				question:"孔明给刘备看了西川多少州的地图，认为此地是建基业之处？",
				selection:["二十四","三十六","四十八","五十四"],
				correct:3
			},
			{
				question:"舌战群儒时，谁第一个向诸葛亮发难？",
				selection:["张昭","虞翻","陆绩","薛综"],
				correct:0
			},
			{
				question:"舌战群儒时，谁认为诸葛亮在效仿苏秦、张仪？",
				selection:["严畯","步骘","陆绩","豪杰"],
				correct:1
			},
			{
				question:"舌战群儒，诸葛亮一举驳倒几个东吴谋士？",
				selection:["五","七","九","十"],
				correct:1
			},
			{
				question:"舌战群儒时，东吴大将何人看不惯，站出来替诸葛亮说话？",
				selection:["黄盖","程普","韩当","甘宁"],
				correct:0
			},
			{
				question:"孔明告诉周瑜《铜雀台赋》是何人所作？",
				selection:["曹操","曹丕","曹植","以上均错"],
				correct:2
			},
			{
				question:"诸葛亮见刘备带了何人来东吴，才放下了心？",
				selection:["赵云","关羽","张飞","以上均错"],
				correct:1
			},
			{
				question:"诸葛亮准备“草船借箭”，问鲁肃借了多少只船？",
				selection:["二十","四十","八十","一百"],
				correct:0
			}
		],
		2:[
			{
				question:"司马懿仿造孔明半月内也造了多少余只“木牛流马”？",
				selection:["五百","一千","一千五百","二千"],
				correct:3
			},
			{
				question:"司马懿将何人捉住，招出另有五人同谋篡逆？",
				selection:["张当","何晏","李胜","毕轨"],
				correct:0
			},
			{
				question:"空城计吓退了司马懿多少大军？",
				selection:["五万","十万","十五万","二十万"],
				correct:2
			},
			{
				question:"曹操所梦的“三马同槽”中除了马腾父子外，还有“一马”是指谁？",
				selection:["马超","司马懿","司马昭","司马师"],
				correct:3
			},
			{
				question:"司马懿字什么？",
				selection:["子明","仲达","德润","伯言"],
				correct:1
			},
			{
				question:"司马懿被曹睿革去兵权时，仅谁信任他？",
				selection:["钟繇","王朗","华钦","曹真"],
				correct:3
			},
			{
				question:"左目下生黑瘤的是何人？",
				selection:["司马懿","司马昭","司马炎","司马师"],
				correct:3
			},
			{
				question:"是谁评价曹操是“治世之能臣，乱世之奸雄”？",
				selection:["曹嵩","骞硕","司马懿","许邵"],
				correct:3
			},
			{
				question:"在火烧连营，使刘备大败的将军是谁？",
				selection:["周瑜","鲁肃","陆逊","司马懿"],
				correct:2
			},
			{
				question:"被诸葛亮困于上方谷的是谁父子三人？",
				selection:["司马懿","司马师","司马昭","司马炎"],
				correct:0
			}
		],
		3:[
			{
				question:"周瑜请诸葛亮几天内完成造箭十万枝？",
				selection:["三","五","七","十"],
				correct:3
			},
			{
				question:"为了求东南风，周瑜还是派了多少精壮军士去给孔明筑七星坛？",
				selection:["五百","八百","一千","一千二百"],
				correct:0
			},
			{
				question:"周瑜间东南风起，立即叫以下何人去把孔明杀了？",
				selection:["甘宁","周泰","蒋钦","丁奉"],
				correct:3
			},
			{
				question:"以下何将年资比周瑜高，但位居其下，故托病不出？",
				selection:["黄盖","程普","韩当","张昭"],
				correct:1
			},
			{
				question:"周瑜最早是听了何人之言后，动了欲杀诸葛亮之念？",
				selection:["鲁肃","张昭","诸葛瑾","太史慈"],
				correct:2
			},
			{
				question:'“群英会”上周瑜令何人执剑作监酒官？',
				selection:["甘宁","蒋钦","周泰","太史慈"],
				correct:3
			},
			{
				question:'周瑜亲自去解彝陵城被围之困，让谁暂代其职？',
				selection:["韩当","甘宁","程普","凌统"],
				correct:3
			},
			{
				question:'甘夫人亡后，孙权依周瑜之计，派何人去刘备处提亲？',
				selection:["鲁肃","张昭","黄盖","吕范"],
				correct:3
			},
			{
				question:'周瑜死后，其灵柩葬于何处？',
				selection:["柴桑","南郡","湖州","芙湖"],
				correct:3
			},
			{
				question:'周瑜被孔明气死时几岁？',
				selection:["三十二 ","三十六","四十","四十四"],
				correct:1
			}
		]
	}
}