class ShopCfg {               
	public static readonly cfgs:CardAttrVo[] = [
		{
			insId:100001,
			model:"",
			cardModel:"card_100001_png",
			level:1,
			name:"关羽",
			cost:200,
			ownNum:0,
			upgradeNum:100,
			quality:4,
			type:CardType.general,
			atk:300,
			hp:1100,
			city:2,
			buffTime:0,
			jieshao:"字云长，河东郡解县人，汜水关温酒斩华雄，虎牢关助张飞战吕布，在曹操麾下时，于白马坡连杀袁绍大将颜良、文丑。攻长沙时与黄忠大战，用拖刀计将黄忠打败。",
			buffDesc:"提升本阵步兵全属性15%",
			buffPrompt:0.15,
			buffCondition:SoldierType.SOLDIER_BU,
			buffAttr:"atk_def",
		},
		// {
		// 	insId:100002,
		// 	model:"",
		// 	cardModel:"card_100002_png",
		// 	level:1,
		// 	name:"马超",
		// 	cost:200,
		// 	ownNum:0,
		// 	upgradeNum:100,
		// 	quality:1,
		// 	type:CardType.general,
		// 	atk:300,
		// 	hp:1050,
		// 	city:2,
		// 	buffTime:0,
		// 	jieshao:"字孟起，西凉马腾之子，伏波将军马援之后，世代为凉州豪族并有爵位。被评为仅次于吕布的猛将，人称“锦马超”。被羌人奉其为“神威天将军”"
		// },
		{
			insId:100011,
			model:"",
			cardModel:"card_100011_png",
			level:1,
			name:"徐晃",
			cost:200,
			ownNum:0,
			upgradeNum:100,
			quality:4,
			type:CardType.general,
			atk:200,
			hp:1200,
			city:1,
			buffTime:0,
			jieshao:"字元让，东汉末年名将，曹魏开国元勋，西汉开国元勋夏侯婴的后代。多次为曹操镇守后方，曾率军民阻断太寿河水，筑陂塘灌溉农田，使百姓受益，功勋卓著",
			buffDesc:"提升本阵步兵防御13%",
			buffPrompt:0.13,
			buffCondition:SoldierType.SOLDIER_BU,
			buffAttr:"def",
		},
		{
			insId:100012,
			model:"",
			cardModel:"card_100012_png",
			level:1,
			name:"典韦",
			cost:200,
			ownNum:0,
			upgradeNum:100,
			quality:4,
			type:CardType.general,
			atk:250,
			hp:950,
			city:1,
			buffTime:0,
			jieshao:"陈留己吾人。被称为古之恶来，曾与许褚大战不分胜负，能逐虎过涧，被胡车儿偷走武器双戟，被反叛的张绣军所杀",
			buffDesc:"提升本阵骑兵攻击力20%",
			buffPrompt:0.2,
			buffCondition:SoldierType.SOLDIER_QI,
			buffAttr:"atk",
		},
		{
			insId:100021,
			model:"",
			cardModel:"card_100021_png",
			level:1,
			name:"太史慈",
			cost:200,
			ownNum:0,
			upgradeNum:100,
			quality:4,
			type:CardType.general,
			atk:200,
			hp:1000,
			city:3,
			buffTime:0,
			jieshao:"字子义，东莱黄县人。东汉末年名将，官至建昌都尉。弓马熟练，箭法精良。孙权统事后，因太史慈能制刘磐，便将管理南方的要务委托给他",
			buffDesc:"提升本阵弓兵攻击力20%",
			buffPrompt:0.2,
			buffCondition:SoldierType.SOLDIER_GONG,
			buffAttr:"atk",
		},
		{
			insId:100022,
			model:"",
			cardModel:"card_100022_png",
			level:1,
			name:"甘宁",
			cost:200,
			ownNum:0,
			upgradeNum:100,
			quality:4,
			type:CardType.general,
			atk:300,
			hp:900,
			city:3,
			buffTime:0,
			jieshao:"字兴霸，巴郡临江人，三国时期孙吴名将，官至西陵太守，折冲将军。他为人仗义疏财，深得士卒拥戴，被陈寿盛赞为“江表之虎臣”",
			buffDesc:"提升本阵骑兵全属性8%",
			buffPrompt:0.08,
			buffCondition:SoldierType.SOLDIER_QI,
			buffAttr:"atk_def",
		},
		{
			insId:10003,
			model:"",
			cardModel:"card_10003_png",
			level:1,
			name:"情报",
			skillIcon:10003,
			cost:80,
			ownNum:0,
			upgradeNum:100,
			quality:1,
			type:CardType.prop,
			atk:0,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"战前布阵所使用，用来打探敌方军情。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		},
		// {
		// 	insId:100041,
		// 	model:"",
		// 	cardModel:"card_100041_png",
		// 	level:1,
		// 	name:"锦囊-趁火打劫",
		// 	skillIcon:100041,
		// 	cost:100,
		// 	ownNum:0,
		// 	upgradeNum:100,
		// 	quality:1,
		// 	type:CardType.special_skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:3000,
		// 	jieshao:"释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// },
		// {
		// 	insId:100042,
		// 	model:"",
		// 	cardModel:"card_100041_png",
		// 	level:1,
		// 	name:"锦囊-趁火打劫",
		// 	skillIcon:100041,
		// 	cost:120,
		// 	ownNum:0,
		// 	upgradeNum:80,
		// 	quality:2,
		// 	type:CardType.special_skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:6000,
		// 	jieshao:"释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// },{
		// 	insId:100043,
		// 	model:"",
		// 	cardModel:"card_100041_png",
		// 	level:1,
		// 	name:"锦囊-趁火打劫",
		// 	skillIcon:100041,
		// 	cost:140,
		// 	ownNum:0,
		// 	upgradeNum:60,
		// 	quality:3,
		// 	type:CardType.special_skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:9000,
		// 	jieshao:"释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// },
		{
			insId:100044,
			model:"",
			cardModel:"card_100041_png",
			level:1,
			name:"锦囊-趁火打劫",
			skillIcon:100041,
			cost:160,
			ownNum:0,
			upgradeNum:40,
			quality:3,
			type:CardType.special_skill,
			atk:0,
			hp:0,
			city:-1,
			buffTime:12000,
			jieshao:"释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		},
		// {
		// 	insId:100051,
		// 	model:"",
		// 	cardModel:"card_100051_png",
		// 	level:1,
		// 	name:"锦囊-美人计",
		// 	skillIcon:100051,
		// 	cost:100,
		// 	ownNum:0,
		// 	upgradeNum:100,
		// 	quality:1,
		// 	type:CardType.special_skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:3000,
		// 	jieshao:"对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// }
		// ,
		// {
		// 	insId:100052,
		// 	model:"",
		// 	cardModel:"card_100051_png",
		// 	level:1,
		// 	name:"锦囊-美人计",
		// 	skillIcon:100051,
		// 	cost:120,
		// 	ownNum:0,
		// 	upgradeNum:80,
		// 	quality:2,
		// 	type:CardType.special_skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:6000,
		// 	jieshao:"对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// }
		// ,
		// {
		// 	insId:100053,
		// 	model:"",
		// 	cardModel:"card_100051_png",
		// 	level:1,
		// 	name:"锦囊-美人计",
		// 	cost:140,
		// 	ownNum:0,
		// 	upgradeNum:60,
		// 	quality:3,
		// 	type:CardType.special_skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:9000,
		// 	jieshao:"对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// },
		{
			insId:100054,
			model:"",
			cardModel:"card_100051_png",
			level:1,
			name:"锦囊-美人计",
			cost:160,
			ownNum:0,
			upgradeNum:40,
			quality:3,
			type:CardType.special_skill,
			atk:0,
			hp:0,
			city:-1,
			buffTime:12000,
			jieshao:"对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		}
		// ,{
		// 	insId:100061,
		// 	model:"",
		// 	cardModel:"card_100061_png",
		// 	level:1,
		// 	name:"暗度陈仓",
		// 	cost:100,
		// 	ownNum:0,
		// 	upgradeNum:100,
		// 	quality:1,
		// 	type:CardType.skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// }
		// ,{
		// 	insId:100062,
		// 	model:"",
		// 	cardModel:"card_100061_png",
		// 	level:1,
		// 	name:"暗度陈仓",
		// 	cost:120,
		// 	ownNum:0,
		// 	upgradeNum:80,
		// 	quality:2,
		// 	type:CardType.skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// },{
		// 	insId:100063,
		// 	model:"",
		// 	cardModel:"card_100061_png",
		// 	level:1,
		// 	name:"暗度陈仓",
		// 	cost:140,
		// 	ownNum:0,
		// 	upgradeNum:60,
		// 	quality:3,
		// 	type:CardType.skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// },
		,{
			insId:100064,
			model:"",
			cardModel:"card_100061_png",
			level:1,
			name:"暗度陈仓",
			cost:160,
			ownNum:0,
			upgradeNum:40,
			quality:3,
			type:CardType.skill,
			atk:0,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		}
		// ,{
		// 	insId:100071,
		// 	model:"",
		// 	cardModel:"card_100071_png",
		// 	level:1,
		// 	name:"擒贼擒王",
		// 	cost:100,
		// 	ownNum:0,
		// 	upgradeNum:100,
		// 	quality:1,
		// 	type:CardType.skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// }
		// ,
		// {
		// 	insId:100072,
		// 	model:"",
		// 	cardModel:"card_100071_png",
		// 	level:1,
		// 	name:"擒贼擒王",
		// 	cost:120,
		// 	ownNum:0,
		// 	upgradeNum:80,
		// 	quality:2,
		// 	type:CardType.skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// }
		// ,{
		// 	insId:100073,
		// 	model:"",
		// 	cardModel:"card_100071_png",
		// 	level:1,
		// 	name:"擒贼擒王",
		// 	cost:140,
		// 	ownNum:0,
		// 	upgradeNum:60,
		// 	quality:3,
		// 	type:CardType.skill,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		// }
		,{
			insId:100074,
			model:"",
			cardModel:"card_100071_png",
			level:1,
			name:"擒贼擒王",
			cost:160,
			ownNum:0,
			upgradeNum:40,
			quality:3,
			type:CardType.skill,
			atk:0,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入战场进行使用)</font>"
		}
		,{
			insId:10008,
			model:"",
			cardModel:"card_10008_png",
			level:1,
			name:"箭塔",
			skillIcon:100081,
			cost:200,
			ownNum:0,
			upgradeNum:50,
			quality:3,
			type:CardType.special_skill,
			atk:60,
			hp:200,
			city:-1,
			buffTime:0,
			jieshao:"依固定间隔而设，作为坚固的据点。并且会发射密集箭雨攻击敌方全部单位"
		}
		,{
			insId:10009,
			model:"",
			cardModel:"card_10009_png",
			level:1,
			name:"投石车",
			skillIcon:100091,
			cost:200,
			ownNum:0,
			upgradeNum:50,
			quality:3,
			type:CardType.special_skill,
			atk:60,
			hp:200,
			city:-1,
			buffTime:0,
			jieshao:"利用配重物的重力发射。出现于中世纪初期，使用至十五世纪，主要用于围攻和防守要塞"
		}
		// ,{
		// 	insId:100101,
		// 	model:"",
		// 	cardModel:"card_hp_png",
		// 	level:1,
		// 	name:"血瓶",
		// 	cost:80,
		// 	ownNum:0,
		// 	upgradeNum:100,
		// 	quality:1,
		// 	type:CardType.prop,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"一次性恢复己方军团20%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
		// }
		// ,
		// {
		// 	insId:100102,
		// 	model:"",
		// 	cardModel:"card_hp_png",
		// 	level:1,
		// 	name:"血瓶",
		// 	cost:100,
		// 	ownNum:0,
		// 	upgradeNum:80,
		// 	quality:2,
		// 	type:CardType.prop,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"一次性恢复己方军团40%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
		// }
		// ,{
		// 	insId:100103,
		// 	model:"",
		// 	cardModel:"card_hp_png",
		// 	level:1,
		// 	name:"血瓶",
		// 	cost:120,
		// 	ownNum:0,
		// 	upgradeNum:60,
		// 	quality:3,
		// 	type:CardType.prop,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"一次性恢复己方军团60%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
		// }
		// ,{
		// 	insId:100104,
		// 	model:"",
		// 	cardModel:"card_hp_png",
		// 	level:1,
		// 	name:"血瓶",
		// 	cost:140,
		// 	ownNum:0,
		// 	upgradeNum:40,
		// 	quality:4,
		// 	type:CardType.prop,
		// 	atk:0,
		// 	hp:0,
		// 	city:-1,
		// 	buffTime:0,
		// 	jieshao:"一次性恢复己方军团80%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
		// },
		,{
			insId:100105,
			model:"",
			cardModel:"card_soldier_1_png",
			level:1,
			name:"西国军",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:1440,
			hp:2880,
			city:-1,
			buffTime:0,
			jieshao:"吴弓兵团，由军中专门招收箭法高超的弓兵精锐所组成。",
			soldierType:1
		}
		,{
			insId:100109,
			model:"",
			cardModel:"card_100109_png",
			level:1,
			name:"白耳军",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:1440,
			hp:2880,
			city:-1,
			buffTime:0,
			jieshao:"吴弓兵团，由军中专门招收箭法高超的弓兵精锐所组成。",
			soldierType:1
		}
		,{
			insId:100110,
			model:"",
			cardModel:"card_100110_png",
			level:1,
			name:"丹阳军",
			cost:20,
			ownNum:200,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:1440,
			hp:2880,
			city:-1,
			buffTime:0,
			jieshao:"吴弓兵团，由军中专门招收箭法高超的弓兵精锐所组成。",
			soldierType:1
		}
        ,{
			insId:100106,
			model:"",
			cardModel:"card_soldier_3_png",
			level:1,
			name:"玄甲骑",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:720,
			hp:2880,
			city:-1,
			buffTime:0,
			jieshao:"效仿魏国虎豹骑所创建的骁勇骑兵团，战斗力极强。",
			soldierType:3
		}
		,{
			insId:100111,
			model:"",
			cardModel:"card_100111_png",
			level:1,
			name:"虎贲军",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:720,
			hp:2880,
			city:-1,
			buffTime:0,
			jieshao:"效仿魏国虎豹骑所创建的骁勇骑兵团，战斗力极强。",
			soldierType:3
		}
		,{
			insId:100112,
			model:"",
			cardModel:"card_100112_png",
			level:1,
			name:"虎贲军",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:720,
			hp:2880,
			city:-1,
			buffTime:0,
			jieshao:"效仿魏国虎豹骑所创建的骁勇骑兵团，战斗力极强。",
			soldierType:3
		}
        ,{
			insId:100107,
			model:"",
			cardModel:"card_soldier_2_png",
			level:1,
			name:"戟士军",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:720,
			hp:3600,
			city:-1,
			buffTime:0,
			jieshao:"皮甲歩卒，古代战争最大数量兵种，可攻可守。",
			soldierType:2
		}
		,{
			insId:100113,
			model:"",
			cardModel:"card_100113_png",
			level:1,
			name:"背嵬军",
			cost:20,
			ownNum:0,
			upgradeNum:40,
			quality:2,
			type:CardType.soldier,
			atk:720,
			hp:3600,
			city:-1,
			buffTime:0,
			jieshao:"皮甲歩卒，古代战争最大数量兵种，可攻可守。",
			soldierType:2
		}
        ,{
			insId:100108,
			model:"",
			cardModel:"card_goods_png",
			level:1,
			name:"粮草",
			cost:300,
			ownNum:0,
			upgradeNum:40,
			quality:1,
			type:CardType.prop,
			atk:500,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"通过税收、内务、商城、副本进行获取。消耗粮草，可进行征兵、战斗。"
		}
		////////
		,{
			insId:100301,
			model:"",
			cardModel:"card_exp_10_png",
			level:1,
			name:"经验100",
			cost:100,
			ownNum:0,
			upgradeNum:40,
			quality:1,
			type:CardType.exp,
			atk:500,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"升级武将"
		}
		,{
			insId:100302,
			model:"",
			cardModel:"card_exp_50_png",
			level:1,
			name:"经验200",
			cost:200,
			ownNum:0,
			upgradeNum:40,
			quality:1,
			type:CardType.exp,
			atk:500,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"升级武将"
		},{
			insId:100303,
			model:"",
			cardModel:"card_exp_100_png",
			level:1,
			name:"经验400",
			cost:400,
			ownNum:0,
			upgradeNum:40,
			quality:1,
			type:CardType.exp,
			atk:500,
			hp:0,
			city:-1,
			buffTime:0,
			jieshao:"升级武将"
		}
	]
}