var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
/**
 * 选将 。属性配置
 * potential 潜力
 * level 。  等级
 * exp 。    经验
 * hp        生命
 * atk       武力
 * brains    智力
 * capacity  容量（带兵数量）
 * type      所带的兵种
 */
var HeroAttrCfg = (function () {
    function HeroAttrCfg() {
    }
    HeroAttrCfg.attrCfg = [
        {
            name: "黄忠",
            potential: 200,
            level: 0,
            curExp: 0,
            exp: 180,
            hp: 1100,
            atk: 200,
            brains: 80,
            capacity: 10,
            curCapacity: 10,
            insId: 100000,
            type: 0,
            icon: "general_0_png",
            index: 0,
        },
        {
            name: "关羽",
            potential: 340,
            level: 0,
            curExp: 0,
            exp: 160,
            hp: 1200,
            atk: 220,
            brains: 90,
            capacity: 10,
            curCapacity: 10,
            insId: 100001,
            type: 1,
            icon: "general_1_png",
            index: 1,
        },
        {
            name: "吕蒙",
            potential: 220,
            level: 0,
            curExp: 0,
            exp: 140,
            hp: 1300,
            atk: 240,
            brains: 100,
            capacity: 10,
            curCapacity: 10,
            insId: 100002,
            type: 2,
            icon: "general_2_png",
            index: 2,
        },
        {
            name: "张飞",
            potential: 100,
            level: 0,
            curExp: 0,
            exp: 120,
            hp: 1400,
            atk: 260,
            brains: 120,
            capacity: 10,
            curCapacity: 10,
            insId: 100003,
            type: 1,
            icon: "general_3_png",
            index: 3,
        },
        {
            name: "周瑜",
            potential: 700,
            level: 0,
            curExp: 0,
            exp: 180,
            hp: 1500,
            atk: 280,
            brains: 80,
            capacity: 10,
            curCapacity: 10,
            insId: 100004,
            type: 0,
            icon: "general_4_png",
            index: 4,
        },
        {
            name: "甘宁",
            potential: 200,
            level: 0,
            curExp: 0,
            exp: 160,
            hp: 1250,
            atk: 210,
            brains: 90,
            capacity: 10,
            curCapacity: 10,
            insId: 100005,
            type: 2,
            icon: "general_5_png",
            index: 5,
        },
        {
            name: "文满",
            potential: 400,
            level: 0,
            curExp: 0,
            exp: 120,
            hp: 1350,
            atk: 260,
            brains: 110,
            capacity: 10,
            curCapacity: 10,
            insId: 100006,
            type: 0,
            icon: "general_6_png",
            index: 6,
        },
        {
            name: "典韦",
            potential: 400,
            level: 0,
            curExp: 0,
            exp: 180,
            hp: 1450,
            atk: 220,
            brains: 80,
            capacity: 10,
            curCapacity: 10,
            insId: 100007,
            type: 1,
            icon: "general_7_png",
            index: 7,
        },
        {
            name: "马超",
            potential: 400,
            level: 0,
            curExp: 0,
            exp: 180,
            hp: 1500,
            atk: 290,
            brains: 80,
            capacity: 10,
            curCapacity: 10,
            insId: 100008,
            type: 2,
            icon: "general_8_png",
            index: 8,
        },
        {
            name: "许褚",
            potential: 400,
            level: 0,
            curExp: 0,
            exp: 160,
            hp: 1200,
            atk: 230,
            brains: 90,
            capacity: 10,
            curCapacity: 10,
            insId: 100009,
            type: 1,
            icon: "general_9_png",
            index: 9,
        },
        {
            name: "吕布",
            potential: 300,
            level: 0,
            curExp: 0,
            exp: 140,
            hp: 1500,
            atk: 300,
            brains: 110,
            capacity: 10,
            curCapacity: 10,
            insId: 100010,
            type: 1,
            icon: "general_10_png",
            index: 10,
        },
        {
            name: "赵云",
            potential: 240,
            level: 0,
            curExp: 0,
            exp: 120,
            hp: 1500,
            atk: 300,
            brains: 120,
            capacity: 10,
            curCapacity: 10,
            insId: 100011,
            type: 2,
            icon: "general_11_png",
            index: 11,
        },
    ];
    return HeroAttrCfg;
}());
__reflect(HeroAttrCfg.prototype, "HeroAttrCfg");
//# sourceMappingURL=HeroAttrCfg.js.map