var RES_RESOURCE = "resource/";
var COMMON_DIR = "resource/res/common/";
var EFFECT = "resource/res/animate/";
var BODY = EFFECT + "body/";
var BOSS = EFFECT + "boss/";
var WEAPON = EFFECT + "weapon/";
var MONSTER = EFFECT + "monster/";
var ITEM = "resource/res/item/";
var MAP_DIR = RES_RESOURCE + "map/";
var CFG_DIR = RES_RESOURCE + "config/";
var SKILL_EFF = EFFECT + "skill/";
var EFFROLESHOW = EFFECT + "show/";
var SOLDIER = EFFECT + "soldier/";
var DEFAULT_FONT = RES_RESOURCE + "res/font/yt.ttf";
//# sourceMappingURL=ResDir.js.map