var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var ShopCfg = (function () {
    function ShopCfg() {
    }
    ShopCfg.cfgs = [
        {
            insId: 100001,
            model: "",
            cardModel: "card_100001_png",
            level: 1,
            name: "关羽",
            cost: 200,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.general,
            atk: 300,
            hp: 1100,
            city: 2,
            buffTime: 0,
            jieshao: "字云长，河东郡解县人，汜水关温酒斩华雄，虎牢关助张飞战吕布，在曹操麾下时，于白马坡连杀袁绍大将颜良、文丑。攻长沙时与黄忠大战，用拖刀计将黄忠打败。"
        },
        {
            insId: 100002,
            model: "",
            cardModel: "card_100002_png",
            level: 1,
            name: "马超",
            cost: 200,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.general,
            atk: 300,
            hp: 1050,
            city: 2,
            buffTime: 0,
            jieshao: "字孟起，西凉马腾之子，伏波将军马援之后，世代为凉州豪族并有爵位。被评为仅次于吕布的猛将，人称“锦马超”。被羌人奉其为“神威天将军”"
        },
        {
            insId: 100011,
            model: "",
            cardModel: "card_100011_png",
            level: 1,
            name: "夏侯惇",
            cost: 200,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.general,
            atk: 200,
            hp: 1200,
            city: 1,
            buffTime: 0,
            jieshao: "字元让，东汉末年名将，曹魏开国元勋，西汉开国元勋夏侯婴的后代。多次为曹操镇守后方，曾率军民阻断太寿河水，筑陂塘灌溉农田，使百姓受益，功勋卓著"
        },
        {
            insId: 100012,
            model: "",
            cardModel: "card_100012_png",
            level: 1,
            name: "典韦",
            cost: 200,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.general,
            atk: 250,
            hp: 950,
            city: 1,
            buffTime: 0,
            jieshao: "陈留己吾人。被称为古之恶来，曾与许褚大战不分胜负，能逐虎过涧，被胡车儿偷走武器双戟，被反叛的张绣军所杀"
        },
        {
            insId: 100021,
            model: "",
            cardModel: "card_100021_png",
            level: 1,
            name: "太史慈",
            cost: 200,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.general,
            atk: 200,
            hp: 1000,
            city: 3,
            buffTime: 0,
            jieshao: "字子义，东莱黄县人。东汉末年名将，官至建昌都尉。弓马熟练，箭法精良。孙权统事后，因太史慈能制刘磐，便将管理南方的要务委托给他"
        },
        {
            insId: 100022,
            model: "",
            cardModel: "card_100022_png",
            level: 1,
            name: "甘宁",
            cost: 200,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.general,
            atk: 300,
            hp: 900,
            city: 3,
            buffTime: 0,
            jieshao: "字兴霸，巴郡临江人，三国时期孙吴名将，官至西陵太守，折冲将军。他为人仗义疏财，深得士卒拥戴，被陈寿盛赞为“江表之虎臣”"
        },
        {
            insId: 10003,
            model: "",
            cardModel: "card_10003_png",
            level: 1,
            name: "锦囊-隔岸观火",
            cost: 80,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "战前布阵所使用，用来打探敌方军情。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100041,
            model: "",
            cardModel: "card_100041_png",
            level: 1,
            name: "锦囊-趁火打劫",
            cost: 100,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 3000,
            jieshao: "释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100042,
            model: "",
            cardModel: "card_100041_png",
            level: 1,
            name: "锦囊-趁火打劫",
            cost: 120,
            ownNum: 0,
            upgradeNum: 80,
            quality: 2,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 6000,
            jieshao: "释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        }, {
            insId: 100043,
            model: "",
            cardModel: "card_100041_png",
            level: 1,
            name: "锦囊-趁火打劫",
            cost: 140,
            ownNum: 0,
            upgradeNum: 60,
            quality: 3,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 9000,
            jieshao: "释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100044,
            model: "",
            cardModel: "card_100041_png",
            level: 1,
            name: "锦囊-趁火打劫",
            cost: 160,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 12000,
            jieshao: "释放毒雾，一定程度的削弱敌军，并造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100051,
            model: "",
            cardModel: "card_100051_png",
            level: 1,
            name: "锦囊-美人计",
            cost: 100,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 3000,
            jieshao: "对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100052,
            model: "",
            cardModel: "card_100051_png",
            level: 1,
            name: "锦囊-美人计",
            cost: 120,
            ownNum: 0,
            upgradeNum: 80,
            quality: 2,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 6000,
            jieshao: "对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100053,
            model: "",
            cardModel: "card_100051_png",
            level: 1,
            name: "锦囊-美人计",
            cost: 140,
            ownNum: 0,
            upgradeNum: 60,
            quality: 3,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 9000,
            jieshao: "对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100054,
            model: "",
            cardModel: "card_100051_png",
            level: 1,
            name: "锦囊-美人计",
            cost: 160,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.special_skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 12000,
            jieshao: "对参战的敌军造成全体眩晕，持续2个回合。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100061,
            model: "",
            cardModel: "card_100061_png",
            level: 1,
            name: "暗度陈仓",
            cost: 100,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        }, {
            insId: 100062,
            model: "",
            cardModel: "card_100061_png",
            level: 1,
            name: "暗度陈仓",
            cost: 120,
            ownNum: 0,
            upgradeNum: 80,
            quality: 2,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        }, {
            insId: 100063,
            model: "",
            cardModel: "card_100061_png",
            level: 1,
            name: "暗度陈仓",
            cost: 140,
            ownNum: 0,
            upgradeNum: 60,
            quality: 3,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        }, {
            insId: 100064,
            model: "",
            cardModel: "card_100061_png",
            level: 1,
            name: "暗度陈仓",
            cost: 160,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放众多地龙，对敌军造成持续性伤害。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100071,
            model: "",
            cardModel: "card_100071_png",
            level: 1,
            name: "擒贼擒王",
            cost: 100,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100072,
            model: "",
            cardModel: "card_100071_png",
            level: 1,
            name: "擒贼擒王",
            cost: 120,
            ownNum: 0,
            upgradeNum: 80,
            quality: 2,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100073,
            model: "",
            cardModel: "card_100071_png",
            level: 1,
            name: "擒贼擒王",
            cost: 140,
            ownNum: 0,
            upgradeNum: 60,
            quality: 3,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 100074,
            model: "",
            cardModel: "card_100071_png",
            level: 1,
            name: "擒贼擒王",
            cost: 160,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.skill,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "释放空中隐藏巨剑，对敌方首领造成巨大创伤。\n<font color=0x00ff00>(拖入敌方区域进行使用)</font>"
        },
        {
            insId: 10008,
            model: "",
            cardModel: "card_10008_png",
            level: 1,
            name: "箭塔",
            cost: 200,
            ownNum: 0,
            upgradeNum: 50,
            quality: 1,
            type: CardType.build,
            atk: 60,
            hp: 200,
            city: -1,
            buffTime: 0,
            jieshao: "依固定间隔而设，作为坚固的据点。箭塔会从平整的城墙中突出，让身在箭塔的防卫者可以沿着城墙面对的方向对外射击"
        },
        {
            insId: 10009,
            model: "",
            cardModel: "card_10009_png",
            level: 1,
            name: "投石车",
            cost: 200,
            ownNum: 0,
            upgradeNum: 50,
            quality: 1,
            type: CardType.build,
            atk: 80,
            hp: 250,
            city: -1,
            buffTime: 0,
            jieshao: "利用配重物的重力发射。出现于中世纪初期，使用至十五世纪，主要用于围攻和防守要塞"
        },
        {
            insId: 100101,
            model: "",
            cardModel: "card_hp_png",
            level: 1,
            name: "血瓶",
            cost: 80,
            ownNum: 0,
            upgradeNum: 100,
            quality: 1,
            type: CardType.prop,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "一次性恢复己方军团20%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
        },
        {
            insId: 100102,
            model: "",
            cardModel: "card_hp_png",
            level: 1,
            name: "血瓶",
            cost: 100,
            ownNum: 0,
            upgradeNum: 80,
            quality: 2,
            type: CardType.prop,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "一次性恢复己方军团40%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
        },
        {
            insId: 100103,
            model: "",
            cardModel: "card_hp_png",
            level: 1,
            name: "血瓶",
            cost: 120,
            ownNum: 0,
            upgradeNum: 60,
            quality: 3,
            type: CardType.prop,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "一次性恢复己方军团60%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
        },
        {
            insId: 100104,
            model: "",
            cardModel: "card_hp_png",
            level: 1,
            name: "血瓶",
            cost: 140,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.prop,
            atk: 0,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "一次性恢复己方军团80%的生命值。\n<font color=0x00ff00>(拖入己方区域进行使用)</font>"
        }, {
            insId: 100105,
            model: "",
            cardModel: "card_soldier_1_png",
            level: 1,
            name: "弓兵",
            cost: 20,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.prop,
            atk: 40,
            hp: 80,
            city: -1,
            buffTime: 0,
            jieshao: "吴弓兵团，由军中专门招收箭法高超的弓兵精锐所组成。"
        },
        {
            insId: 100106,
            model: "",
            cardModel: "card_soldier_2_png",
            level: 1,
            name: "骑兵",
            cost: 20,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.prop,
            atk: 30,
            hp: 120,
            city: -1,
            buffTime: 0,
            jieshao: "效仿魏国虎豹骑所创建的骁勇骑兵团，战斗力极强。"
        },
        {
            insId: 100107,
            model: "",
            cardModel: "card_soldier_3_png",
            level: 1,
            name: "步兵",
            cost: 20,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.prop,
            atk: 20,
            hp: 100,
            city: -1,
            buffTime: 0,
            jieshao: "皮甲歩卒，古代战争最大数量兵种，可攻可守。"
        },
        {
            insId: 100108,
            model: "",
            cardModel: "card_goods_png",
            level: 1,
            name: "粮草",
            cost: 300,
            ownNum: 0,
            upgradeNum: 40,
            quality: 4,
            type: CardType.prop,
            atk: 500,
            hp: 0,
            city: -1,
            buffTime: 0,
            jieshao: "通过税收、内务、商城、副本进行获取。消耗粮草，可进行征兵、战斗。"
        }
    ];
    return ShopCfg;
}());
__reflect(ShopCfg.prototype, "ShopCfg");
//# sourceMappingURL=ShopCfg.js.map