var RES_RESOURCE = "resource/";
var COMMON_DIR = "resource/res/common/";
var EFFECT = "resource/res/animate/";
var ITEM = "resource/res/item/";
var MAP_DIR = RES_RESOURCE + "map/";
var CFG_DIR = RES_RESOURCE + "config/";
var SKILL_EFF = EFFECT + "skill/";
var EFFROLESHOW = EFFECT + "show/";
var SOLDIER = EFFECT + "soldier/";
var DEFAULT_FONT = RES_RESOURCE + "res/font/yt.ttf";
var EQUIP_ICON = RES_RESOURCE + "res/view/battleView/equipIcon/";
var LEVEL_ICON = RES_RESOURCE + "res/view/battleView/levelIcon/";
var SKILL_EFF_ICON = RES_RESOURCE + "res/view/battleView/skillpic/";
var VIDEO_EFF_ICON = RES_RESOURCE + "res/video/";
//# sourceMappingURL=ResDir.js.map