class ClothesConfig {
	public static clothesFig: any[] = [
		{
			"id": "1001",
			"name": "紫绡翠纹裙",
			"state": 0,
			"enjingyan": 6,
			"encoin": 25,
			"enyouwan": 20,
			"byweifen": 0,
			"bycoin": 600,
			"wellSay": "既含睇兮又宜笑\n子慕予兮善窈窕",
			"header": "img_icon_head_normal_01",
			"half": "img_syn_half_normal_01",
			"image": "img_cloth_list_normal_01"
		},
		{
			"id": "1002",
			"name": "苏绣月华锦",
			"state": 0,
			"enjingyan": 5,
			"encoin": 10,
			"enyouwan": 30,
			"byweifen": 4,
			"bycoin": 500,
			"wellSay": "戴金翠之首饰\n缀明珠以耀躯",
			"header": "img_icon_head_normal_02",
			"half": "img_syn_half_normal_02",
			"image": "img_cloth_list_normal_02"
		},
		{
			"id": "1003",
			"name": "白玉兰散花纱",
			"state": 0,
			"enjingyan": 5,
			"encoin": 10,
			"enyouwan": 20,
			"byweifen": 4,
			"bycoin": 400,
			"wellSay": "仿佛兮若轻云之蔽月\n飘飘兮若流风之回雪",
			"header": "img_icon_head_normal_03",
			"half": "img_syn_half_normal_03",
			"image": "img_cloth_list_normal_03"
		},
		{
			"id": "1004",
			"name": "细羽织锦披风",
			"state": 0,
			"enjingyan": 6,
			"encoin": 15,
			"enyouwan": 25,
			"byweifen": 5,
			"bycoin": 500,
			"wellSay": "罗衣何飘飘\n轻裾随风还",
			"header": "img_icon_head_normal_04",
			"half": "img_syn_half_normal_04",
			"image": "img_cloth_list_normal_04"
		},
		{
			"id": "1005",
			"name": "烟纹碧霞罗衣",
			"state": 0,
			"enjingyan": 6,
			"encoin": 20,
			"enyouwan": 30,
			"byweifen": 6,
			"bycoin": 600,
			"wellSay": "炉边人似月\n皓腕凝霜雪",
			"header": "img_icon_head_normal_05",
			"half": "img_syn_half_normal_05",
			"image": "img_cloth_list_normal_05"
		},
		{
			"id": "1006",
			"name": "烟罗紫霞裳",
			"state": 0,
			"enjingyan": 7,
			"encoin": 15,
			"enyouwan": 35,
			"byweifen": 7,
			"bycoin": 700,
			"wellSay": "愿在裳而为带\n束窈窕之纤身",
			"header": "img_icon_head_normal_06",
			"half": "img_syn_half_normal_06",
			"image": "img_cloth_list_normal_06"
		},
		{
			"id": "1007",
			"name": "曳地水袖长裙",
			"state": 0,
			"enjingyan": 8,
			"encoin": 18,
			"enyouwan": 40,
			"byweifen": 10,
			"bycoin": 800,
			"wellSay": "春寒赐浴华清池\n温泉水滑洗凝脂",
			"header": "img_icon_head_normal_07",
			"half": "img_syn_half_normal_07",
			"image": "img_cloth_list_normal_07"
		},
		{
			"id": "1008",
			"name": "绿霞花娇纱裙",
			"state": 0,
			"enjingyan": 10,
			"encoin": 20,
			"enyouwan": 50,
			"byweifen": 11,
			"bycoin": 1000,
			"wellSay": "裙裙旋旋手迢迢\n不趋音色自趋娇",
			"header": "img_icon_head_normal_08",
			"half": "img_syn_half_normal_08",
			"image": "img_cloth_list_normal_08"
		},
		{
			"id": "1009",
			"name": "紫羽绣衫罗裙",
			"state": 0,
			"enjingyan": 10,
			"encoin": 20,
			"enyouwan": 50,
			"byweifen": 11,
			"bycoin": 1000,
			"wellSay": "回眸一笑百媚生\n六宫粉黛无颜色",
			"header": "img_icon_head_normal_09",
			"half": "img_syn_half_normal_09",
			"image": "img_cloth_list_normal_09"
		}
	]
}